trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  displayName: Run tests
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.JAVA_VERSION'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: Bash@3
  displayName: Update GIT url and commit
  inputs:
    targetType: 'inline'
    script: |
      set -x
      yq -i '.spec.source.git.url = "$(Build.Repository.Uri)" | .spec.source.git.ref.commit = "$(Build.SourceVersion)"' config/workload.yaml

- task: Kubernetes@1
  displayName: Apply Workload
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'YOUR_KUBERNETES_SERVICE_ENDPOINT'
    namespace: 'NAMESPACE'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'config/workload.yaml'

