apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: example-app
  annotations:
    autoscaling.knative.dev/min-scale: "1"
  labels:
    app.kubernetes.io/part-of: example-app
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
spec:
  source:
    git:
      url: https://github.com/...git
      ref:
        branch: main
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  serviceClaims:
    - name: auth-client
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: auth-client
  
    # A shared session storage is required for OAuth2 clients if multiple instances of the app are run behind a load balancer
    - name: shared-session-storage
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: redis-1